<?php
/** @var \Magento\Framework\View\Element\Template $block */
?>
<div class="static-page-content">
    <div class="inside_block_text_and_image static-page-grey-box-text">
        <div class="inside_block_text_content">
            <div class="italic_24_text">Our current delivery times are at least 3–4 weeks on newly manufactured products.</div>
            <div>
                <p>
                    However many of our products already held in stock can be shipped next day direct from our UK warehouse. For products not stocked, current delivery times are 3-4 weeks. Customised or bespoke products may take longer, depending on their size or complexity.
                </p>
                <p>
                    If you require an order to be shipped outside of the UK, please contact us. We endeavour to fulfil all delivery requests and are committed to providing you with the best service possible.
                </p>
            </div>

        </div>
        <img src="<?= $block->getViewFileUrl('Magento_Cms::images/delivery/delivery.jpg'); ?>" alt="Culture"/>
    </div>
</div>

<div class="center_content">
    <p class="italic_24_text ">For any delivery related questions, please contact us.</p>
    <a href="mailto: sales@davidhuntlighting.co.uk" class="button ">sales@davidhuntlighting.co.uk</a>
</div>


