<?php
/** @var \Magento\Framework\View\Element\Template $block */
?>
<a name="craftsmanship"></a>
<div class="static-page-content">
    <div class="cms-bespoke-bottom_content">

        <div class="vertical-side-line-container"><span class="vertical-side-line"><?= __("Our Story"); ?></span></div>

        <img src="<?= $block->getViewFileUrl('Magento_Cms::images/story/craftsmanship.jpg'); ?>" alt="Culture"/>

        <div class="static-page-grey-box-text">
            <div >
                <h2 class="small-uppertitle">Uncompromising</h2>
                <h1 class="small-underline">Craftsmanship</h1>

                <p>Our 300 year history is founded upon a proud tradition of British hand craft. Comprising a team of
                    experienced artisans including painters, sculptors and metalworkers, we can ensure the utmost level
                    of care and expertise is given to every design made inside our Cotswolds workshop.</p>

                <a href="<?= $block->getUrl('craftsmanship') ?>" class="button">Learn more</a>
            </div>
        </div>
    </div>
</div>
