<?php
/** @var \Magento\Framework\View\Element\Template $block */
?>
<div class="static_box_black_text_image">
    <div class="static_box_black_text_image_text_content story_top_box">
        <div class="static_box_black_text_image_text">
            <h2 class="small-uppertitle">Our</h2>
            <h1 class="small-underline">Story</h1>
            <p>
                David Hunt Lighting is a true British heritage brand with a provenance of over 300 years. Discover our
                historic beginnings, learn about our artisanal core and explore how we combine all of this in order to
                offer a range of services from personalised to completely bespoke.
            </p>
            <div class="static_box_black_text_image_buttons">
                <a href="#heritage" class="button">Heritage</a>
                <a href="#craftsmanship" class="button">Craftsmanship</a>
                <a href="#bespoke" class="button">Bespoke</a>
            </div>
        </div>
    </div>

    <img src="<?= $block->getViewFileUrl('Magento_Cms::images/story/story.jpg'); ?>" alt="Story"/>
</div>
