<div class="mp-sidebar">
    <div class="block-title col-xs-12 sidebar-categories">
        <p class="block-mp-sidebar-heading" role="heading" aria-level="2">Follow</p>
    </div>
    <div class="blog-follow-links grey_socials">
        <a href="https://www.instagram.com/davidhuntlighting" target="_blank"><i class="instagram-link">&nbsp;</i></a>
        <a href="https://twitter.com/DavidHuntLights" target="_blank"><i class="instagram-linkedin">&nbsp;</i></a>
        <a href="https://www.facebook.com/DavidHuntLighting" target="_blank"><i class="instagram-facebook">&nbsp;</i></a>
        <a href="https://ro.pinterest.com/davidhuntlights/" target="_blank"><i class="instagram-pinterest">&nbsp;</i></a>
    </div>
</div>
