<?php
/** @var $block \Fyb\Theme\Block\StoreInfo */
?>

<div class="footer_item_content_contact">
    <div class="footer-title">Contact</div>
    <div class="footer-contact-content footer-links">
        <ul class="links-list">
            <li>Third Floor Centre Dome<br>
                Design Centre <br>
                Chelsea Harbour <br>
                Lots Road <br>
                London, SW10 0XE</li>
        </ul>
        <div>
            <a href="https://www.instagram.com/davidhuntlighting" target="_blank"><i class="instagram-link">&nbsp;</i></a>
            <a href="https://twitter.com/DavidHuntLights" target="_blank"><i class="instagram-linkedin">&nbsp;</i></a>
            <a href="https://www.facebook.com/DavidHuntLighting" target="_blank"><i class="instagram-facebook">&nbsp;</i></a>
            <a href="https://ro.pinterest.com/davidhuntlights/" target="_blank"><i class="instagram-pinterest">&nbsp;</i></a>
        </div>

        <a class="button" href="https://www.darlighting.com/customer/account/DHLlogin/">TRADE PARTNERS</a>
    </div>
</div>
