<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<small class="copyright">
    <div class="copyright_content">
        <p>
           <?= $block->escapeHtml($block->getCopyright()) . ' | ' ?>
            <a href="<?= $block->getUrl('terms-and-conditions') ?>">Terms & Conditions</a> |
            <a href="<?= $block->getUrl('privacy-policy-cookie-restriction-mode') ?>">Privacy Policy</a> |
            <a href="<?= $block->getUrl('enable-cookies') ?>">Cookie Policy</a> |
            <a href="<?= $block->getUrl('returns-and-online-shop-terms') ?>">Returns and Online Shop Terms</a>
        </p>
        <p>Created by Rak Design</p>
    </div>
</small>
