<a name="customize"></a>
<div class="homepage-customise">

    <img src="<?= $block->getViewFileUrl('Magento_Cms::images/customize.jpg') ?>" alt="Customise"/>
    <div class="homepage-customise-text-container">
        <div class="homepage-customise-text">
            <div>
                <h2 class="small-uppertitle">Customise</h2>
                <h1 class="small-underline-small-text">Personalise your own fitting from our range</h1>

            </div>
            <div class="homepage-customise-text-steps">
                <div>
                    <h3>01</h3>
                    <span>
                        <h5>You Design It</h5>
                        <span>Start with a blank canvas and choose your finish, colour and accessories.</span>
                    </span>
                </div>
                <div>
                    <h3> 02</h3>
                    <span>
                        <h5> We Make It</h5>
                        <span>We’ll follow your exact specifications to make your vision a reality.</span>
                    </span>
                </div>
                <div>
                    <h3>03</h3>
                    <span>
                        <h5>It's Delivered</h5>
                        <span>Your unique design will be delivered to you within 30 days.</span>
                    </span>
                </div>
            </div>
            <div>
                <p>
                    Our online product configurator is a great destination to begin your design journey with us,
                    offering options on a range of finishes and features for many of our flagship ranges.
                </p>
            </div>

        </div>
        <a href="https://customise.davidhuntlighting.co.uk/" class="button">CUSTOMISE</a>
        <a href="#instagram" class="vertical-arrow-button white">
            <?= __("Instagram") ?>
        </a>
    </div>
    <div class="homepage-customise-container-button">
        <div class="homepage-fullwidth-leftspace">
            <div class="homepage-customise-container-grid">
                <div></div>
                <div><a href="https://customise.davidhuntlighting.co.uk/" class="button">CUSTOMISE</a></div>
            </div>
        </div>
    </div>
</div>
