<div class="homepage-inspire">
    <a href="#newcollection" class="vertical-arrow-button">
        <?= __("New Collection") ?>
    </a>
    <div class="homepage-inspire-content">
        <div>
            <div class="homepage-inspire-content-item">
                <h3>Heritage</h3>
                <p>David Hunt Lighting is a true British heritage brand with a provenance of over 300 years. Discover our historic beginnings and how we have developed up to the present day. </p>
                <a  class="button" href="<?= $block->getUrl('heritage') ?>">LEARN MORE</a>
            </div>
            <div class="homepage-inspire-content-item">
                <h3>Craftsmanship</h3>
                <p>From the very beginning of the David Hunt Lighting story, our guiding principles, values and vision have remained a constant source of inspiration.  </p>
                <a   class="button" href="<?= $block->getUrl('craftsmanship') ?>">LEARN MORE</a>
            </div>
            <div class="homepage-inspire-content-item">
                <h3>Bespoke</h3>
                <p>Almost every single David Hunt Lighting product is made to order at our Cotswolds workshop.<br/>
                    Explore our full range of personalisation options, ranging from partially to fully bespoke.
                </p>
                <a   class="button" href="<?= $block->getUrl('bespoke') ?>">LEARN MORE</a>
            </div>

        </div>
        <div class="homepage-inspire-images">
            <div  class="homepage-inspire-images-col-1">
                <img src="<?= $block->getViewFileUrl('Magento_Cms::images/inspire_1.jpg') ?>" alt="David Hunt Lightning Factory Visit" />
            </div>
            <div class="homepage-inspire-images-col-2">
                <div  class="homepage-inspire-images-col-2-1"><img src="<?= $block->getViewFileUrl('Magento_Cms::images/inspire_3.jpg') ?>" alt="David Hunt Lightning Factory Visit" /></div>
                <div  class="homepage-inspire-images-col-2-2"><img src="<?= $block->getViewFileUrl('Magento_Cms::images/inspire_2.jpg') ?>" alt="David Hunt Lightning Factory Visit" /></div>
            </div>


        </div>
    </div>
    <div class="clearfix"></div>
</div>

