<div class="aname_position"><a name="getintouch"></a></div>
<div class="homepage-ourinfo">
    <div class="homepage-ourinfo-catalogue homepage-ourinfo-text">
        <h3>Our Catalogue</h3>
        <span>Updated yearly in line with our main design launch, our catalogue gives a complete overview of our beautiful individual ranges.</span>
        <div class=" homepage-ourinfo-text-buttons">
            <a class="button" href="<?= $block->getUrl('catalogues') ?>">View Online</a>
            <a  class="button" href="<?= $block->getUrl('catalogues') ?>">Order</a>
        </div>
    </div>
    <div class="homepage-ourinfo-swatches homepage-ourinfo-text">
        <h3>Our swatches</h3>
        <span>View our surface finishes, signature colour palette and fabrics in more detail and learn what makes each of them so important to our design process.</span>
        <div class=" homepage-ourinfo-text-buttons">
            <a  class="button" href="<?= $block->getUrl('our-swatches') ?>">View Online</a>
            <a  class="button" href="<?= $block->getUrl('our-swatches') ?>">Order</a>
        </div>
    </div>
    <div class="homepage-ourinfo-stocklist homepage-ourinfo-text">
        <h3>Find a stockist</h3>
        <span>Explore our exclusive partner network comprising some of Britain’s finest lighting showrooms.</span>
        <div class=" homepage-ourinfo-text-buttons">
            <a  class="button" href="<?= $block->getUrl('stockist') ?>"">SEARCH</a>
        </div>
    </div>
    <div  class="homepage-ourinfo-contact homepage-ourinfo-text">
        <h3>Contact us</h3>
        <span>For general enquiries or anything else, please contact our friendly and knowledgeable team.</span>
        <div class=" homepage-ourinfo-text-buttons">
            <a class="button"  href="<?= $block->getUrl('contact') ?>">CONTACT</a>
        </div>
    </div>

</div>
