<a name="showroom"></a>
<div class="homepage-showroom homepage-fullwidth-leftspace">
    <a href="#getintouch" class="vertical-arrow-button">
        <?= __("GET IN TOUCH") ?>
    </a>
    <div class="homepage-showroom-text-container">
        <h2 class="small-uppertitle">Visit our</h2>
        <h1 class="small-underline">Showroom</h1>
        <span>We have showrooms both on site at our workshop in Shipston on Stour, as well as the exclusive Design Centre Chelsea Harbour, where our knowledgeable and friendly team can advise you on all things David Hunt Lighting. </span>
        <a class="button" href="<?= $block->getUrl('find-us') ?>">PLAN A VISIT</a>
    </div>
    <div class="homepage-showroom-image-container">
        <div>
            <img src="<?= $block->getViewFileUrl('Magento_Cms::images/showroom/Visit-Our-Showroom-London-1.jpg'); ?>"
                 alt="London Showroom"/>

                <h5>LONDON SHOWROOM</h5>
                <span> Third Floor, Centre Dome, Design Centre, Chelsea Harbour, Lots Road, London SW10 0XE
</span>

        </div>
        <div>
            <img src="<?= $block->getViewFileUrl('Magento_Cms::images/showroom/Visit-Our-Showroom-Shipston-1.jpg'); ?>"
                 alt="Trade Showroom"/>

                <h5>SHIPSTON ON STOUR SHOWROOM</h5>
                <span>Tilemans Lane, Shipston on Stour Warwickshire CV36 4HP</span>

        </div>
    </div>
    <div class="homepage-showroom-link-container">
        <a class="button" href="<?= $block->getUrl('showroom') ?>">PLAN A VISIT</a>
    </div>
</div>
