<?php
/** @var \Magento\Framework\View\Element\Template $block */
?>
<div class="cms-catalogue-content">
    <div  class="cms-catalogue-content-text-container">
        <div class="cms-catalogue-content-text">
            <h2 class="small-uppertitle">Our</h2>
            <h1 class="small-underline">Catalogues</h1>
            <p>
                Here you can view all of our latest brochures, look books and swatch cards.
                Our literature is updated each season, so be sure to check back for updates.
                You can also purchase hard copies of our catalogues and swatch books using
                the links provided.
            </p>
        </div>
    </div>

        <img src="<?= $block->getViewFileUrl('Magento_Cms::images/catalogues/Our-Catalogues-Header-1.jpg'); ?>" alt="Catalogues" />

</div>
