<?php
/** @var \Magento\Framework\View\Element\Template $block */
?>

<div class="static-page-content swatches-samples">
    <div class="swatches-samples-description">
        <span>For more information or to discuss your own bespoke fabric requirements with our team, please contact sales@davidhuntlighting.co.uk</span>
    </div>
<!--    <div class="center_page-buttons">-->
<!--        <a href="#" class="button">ORDER SAMPLES</a>-->
<!--        <a href="#" class="button">DOWNLOAD PDF</a>-->
<!--    </div>-->
</div>
