<?php
/** @var \Magento\Framework\View\Element\Template $block */
?>
<div class="static-page-content swatches-samples">
    <div class="swatches-samples-description">
        <span>
            Owing to many years of experimentation and refinement, we are now considered leaders in this area, and so invite you to explore our finishes in more detail below
        </span>
    </div>
<!--    <div class="center_page-buttons">-->
<!--        <a href="#" class="button">ORDER SAMPLES</a>-->
<!--        <a href="#" class="button">DOWNLOAD PDF</a>-->
<!--    </div>-->
</div>
