<?php
/** @var \Magento\Framework\View\Element\Template $block */
?>
<div class="static_box_black_text_image">
    <div class="static_box_black_text_image_text_content">
        <div class="static_box_black_text_image_text">
            <h2 class="small-uppertitle">Our</h2>
            <h1 class="small-underline">Swatches</h1>
            <p>
                Some of the hallmarks of a David Hunt Lighting product are our distinctive
                surface finishes, signature colour palette and curated choice of fabric and lining
                options. Here you can view these elements in more detail and learn what
                makes each so important to our design process.
            </p>
            <div class="static_box_black_text_image_buttons">
                <a href="#fabrics" class="button">VIEW FABRICS</a>
            </div>
        </div>
    </div>

    <img src="<?= $block->getViewFileUrl('Magento_Cms::images/swatches/swatches.jpg'); ?>" alt="Swatches"/>

</div>
