<div class="homepage-inspire">
    <a href="#newcollection" class="vertical-arrow-button">
        <?= __("New Collection") ?>
    </a>
    <div class="homepage-inspire-content">
        <div>
            <div class="homepage-inspire-content-item">
                <h3>Handmade in Britain</h3>
                <p>Based in Oxfordshire, our experienced team of shade makers meticulously construct each of our lampshades exclusively by hand.</p>
                <a  class="button" href="<?= $block->getUrl('handmade-britain') ?>">LEARN MORE</a>
            </div>
            <div class="homepage-inspire-content-item">
                <h3>Premium Quality</h3>
                <p>The best lampshades begin with the finest materials. Discover our curated range of luxury fabrics, which are used on all of our in-house lampshades. </p>
                <a   class="button" href="<?= $block->getUrl('premium-quality') ?>">LEARN MORE</a>
            </div>
            <div class="homepage-inspire-content-item">
                <h3>Bespoke Ordering</h3>
                <p>For those who like to be a little different, we also offer a fully bespoke service for customers supplying their own fabrics.
                </p>
                <a   class="button" href="<?= $block->getUrl('bespoke-ordering') ?>">LEARN MORE</a>
            </div>

        </div>
        <div class="homepage-inspire-images">
            <div  class="homepage-inspire-images-col-1">
                <img src="<?= $block->getViewFileUrl('Magento_Cms::images/inspire_1.jpg') ?>" alt="Handmade in Britain" />
            </div>
            <div class="homepage-inspire-images-col-2">
                <div  class="homepage-inspire-images-col-2-1"><img src="<?= $block->getViewFileUrl('Magento_Cms::images/inspire_3.jpg') ?>" alt="Handmade in Britain" /></div>
                <div  class="homepage-inspire-images-col-2-2"><img src="<?= $block->getViewFileUrl('Magento_Cms::images/inspire_2.jpg') ?>" alt="Handmade in Britain" /></div>
            </div>


        </div>
    </div>
    <div class="clearfix"></div>
</div>

