<a name="instagram"></a>
<div class="homepage-instagram homepage-fullwidth-leftspace">
    <div class="homepage-instagram-title">
        <h1 class="small-underline">Instagram</h1>
        <div><a class="button" href="https://www.instagram.com/thelightshadestudio" target="_blank">Follow Us</a></div>

    </div>

    <script src="https://static.elfsight.com/platform/platform.js" data-use-service-core defer></script> <div class="elfsight-app-5afe0aa2-6c57-44b3-9727-76600ceb778d" data-elfsight-app-lazy></div>

    <div class="homepage-instagram-bottom-link"><a class="button" href="https://www.instagram.com/thelightshadestudio" target="_blank">Follow Us</a></div>
</div>

