<?php
/** @var \Magento\Framework\View\Element\Template $block */
?>
<div class="static-page-content">
    <div class="showroom-content-boxes">
        <div>

            <img src="<?= $block->getViewFileUrl('Magento_Cms::images/showroom/Visit-Our-Showroom-London-1.jpg'); ?>"
                 alt="London Showroom"/>
            <div class="showroom-content-boxes-text">
                <h5 class="italic_24_text">London Showroom</h5>
                <div class="showroom-content-boxes-text-details">
                    <div class="showroom-content-boxes-text-details-1">
                        <div>
                            <p>Monday - Friday</p>
                            <p>09:30–17:00</p>
                         <a href="tel:+44(0)20 7349 8111">+44(0)20 7349 8111</a>
                        </div>

                        <address>
                            DAVID HUNT LIGHTING<br/>
                            Third Floor, Centre Dome<br/>
                            Design Centre, Chelsea Harbour<br/>
                            London<br/>
                            SW10 0XE
                        </address>
                    </div>

                    <div class="showroom-content-boxes-text-details-2">
                        <p>
                            The Design Centre, Chelsea Harbour is the world’s premier destination for design and decoration, the largest of its kind in Europe. It is considered the first port of call for professional designers and architects sourcing for prestigious residential and commercial projects, as well as design enthusiasts seeking inspiration for their own homes. We are exceptionally proud to host our newly renovated showroom here amongst a thriving community of peers.
                        </p>
                    </div>
                </div>
            </div>
        </div>

        <div>
            <img src="<?= $block->getViewFileUrl('Magento_Cms::images/showroom/Visit-Our-Showroom-Shipston-1.jpg'); ?>"
                 alt="Trade Showroom"/>
            <div class="showroom-content-boxes-text">
                <h5 class="italic_24_text">Trade Showroom</h5>
                <div class="showroom-content-boxes-text-details">
                    <div class="showroom-content-boxes-text-details-1">
                        <div>
                            <p>(by appointment only)</p>
                        <a href="tel:+44(0)1295 672 627">+44(0)1295 672 627</a>
                        </div>

                        <address>
                            DAVID HUNT LIGHTING<br/>
                            Swan Close Road<br/>
                            Banbury<br/>
                            Oxfordshire<br/>
                            OX16 5AQ
                        </address>
                    </div>

                    <div class="showroom-content-boxes-text-details-2">
                        <p>
                            Based in our neighbouring county of Oxfordshire, our trade showroom offers an alternative venue to that of our London showroom for those based closer to the South Midlands area.
                            We maintain a comprehensive gallery that is updated annually and features many of our best-known design collections. Please contact our sales team to arrange an exclusive visit, which are by appointment only.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
