<?php
/** @var \Magento\Framework\View\Element\Template $block */
?>

<div class="static-page-content clearfix">
    <div class="static_text_3images">
        <div>
            <h2 class="small-uppertitle">Premium  </h2>
            <h1 class="small-underline">Quality</h1>
            <p>
                Shading is a crucial stage in the journey of creating a light fitting. Whilst not all lighting will require shades, the ones that do are often the most memorable. We understand that with so many options in terms of size, shape, colour and material to choose from, shading can sometimes feel intimidating! We have spent years developing and refining our lampshades and now consider ourselves to be expert in this area.
            </p>
            <p>Our collection hosts a hand–picked range of woven cottons, luxury satins, dupion silks and pure linens, each finished in a wide variety of both rich and subtle natural dyes. We work alongside British-based fabric suppliers who share our passion for craft and source only the finest materials in order to guarantee quality and longevity on all of our lampshades.  </p>

        </div>
        <div class="static_text_3images-images">
            <div class="static_text_3images-images-col-1"><img src="<?= $block->getViewFileUrl('Magento_Cms::images/premium/premium_1.jpg'); ?>" alt="Bespoke 1"/></div>
            <div class="static_text_3images-images-col-2">
                <div class="static_text_3images-images-col-2-1"><img src="<?= $block->getViewFileUrl('Magento_Cms::images/premium/premium_2.jpg'); ?>" alt="Bespoke 2"/></div>
                <div class="static_text_3images-images-col-2-2"><img src="<?= $block->getViewFileUrl('Magento_Cms::images/premium/premium_3.jpg'); ?>" alt="Bespoke 3"/></div>
            </div>


        </div>
    </div>
</div>
