<?php $settings = $block->getSettings(); ?>
<?php if ($settings): ?>

    <div class="ajax-call grid-gap no-padding-top">
        <div class="row row-flex grid-row-big">
            <div class="col-md-6">
                <div class="detailed-base tech-data-configurator">

                </div>
            </div>
            <div class="col-md-6">
                <div class="detailed-shade tech-data-configurator">

                </div>
            </div>
        </div>

        <div class="row grid-row-big grid-gap no-padding-bottom">
            <div class="col-md-6">
                <div class="measurement-image-base tech-image-configurator">
                    <div class="main-image"></div><div class="thumb-images owl-theme owl-carousel"></div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="measurement-image-shade tech-image-configurator">
                    <div class="main-image"></div><div class="thumb-images owl-theme owl-carousel"></div>
                </div>
            </div>
        </div>

    </div>
<?php endif; ?>
