<?php
/** @var \Magento\Framework\View\Element\Template $block */
?>
<div class="static-page-content cms-bespoke-bottom_content">
    <div class="vertical-arrow-button ">
        <?= __("BESPOKE"); ?>
    </div>

    <img src="<?= $block->getViewFileUrl('Magento_Cms::images/bespoke/culture.jpg'); ?>" alt="Culture" />

    <div class="static-page-greydark-box-text">


        <div class="static-page-bigger_text">
                We have manufactured pieces for countless such eventualities, and our team thrive on partnering with clients to achieve their design goals. If you have a project in mind, no matter the size or complexity, we welcome your enquiry.
        </div>


    </div>
</div>
