<?php
/** @var \Magento\Framework\View\Element\Template $block */
$customizeHelper = $this->helper(\Fyb\Customizer\Helper\Data::class);
?>
<div class="cms-bespoke-foter_content">
    <div>
        <span>
            Why not explore our configurable range today? If you require any further guidance on how to specify a product then our team or trade partners will be happy to help you further.
        </span>
    </div>
    <div>
        <a href="<?= $customizeHelper->getCustomizeLink() ?>" class="button grey">CUSTOMISE</a>
        <a href="<?= $block->getUrl('contact') ?>" class="button ">CONTACT US</a>
    </div>
</div>
