<?php
/** @var \Magento\Framework\View\Element\Template $block */
?>

<div class="static-page-content clearfix">
    <div class="static_text_3images">
        <div>
            <h2 class="small-uppertitle">Truly</h2>
            <h1 class="small-underline">Bespoke</h1>
            <p>
                Our online product configurator is a great place to begin your design journey with us, offering options on a range of features for many of our flagship ranges. More often than not, we find that our customer’s needs are met through this process alone, with many finding our choice of finishes, palette colours and fabrics an ample solution for their requirements.
            </p>
            <p>
                If however you are looking for something that perfectly complements your interior space or style, we also offer a comprehensive bespoke service. By using industry-standard colour referencing systems including RAL or Dulux colour matching, we can tailor any of our fittings to a chosen colour way. Our ability to apply metallics to castings means that we can offer many of our resin fittings in metallic finishes beyond those featured in our published range. If you have a particularly large space that demands an oversized piece to make a statement, we are also able to adapt existing designs to cater for this too.
            </p>
        </div>
        <div class="static_text_3images-images">
            <div class="static_text_3images-images-col-1"><img src="<?= $block->getViewFileUrl('Magento_Cms::images/bespoke/truly_1.jpg'); ?>" alt="Truly 1"/></div>
            <div class="static_text_3images-images-col-2">
                <div class="static_text_3images-images-col-2-1"><img src="<?= $block->getViewFileUrl('Magento_Cms::images/bespoke/truly_3.jpg'); ?>" alt="Truly 2"/></div>
                <div class="static_text_3images-images-col-2-2"><img src="<?= $block->getViewFileUrl('Magento_Cms::images/bespoke/truly_2.jpg'); ?>" alt="Truly 3"/></div>
            </div>


        </div>
    </div>
</div>
