<?php
/** @var \Magento\Framework\View\Element\Template $block */
?>
<div class="static-page-content craftmanship-bottom_content">
    <div class="vertical-side-line-container"><span class="vertical-side-line"><?= __("CRAFTSMANSHIP"); ?></span></div>


        <img src="<?= $block->getViewFileUrl('Magento_Cms::images/craftsmanship/culture.jpg'); ?>" alt="Culture" />

    <div class="static-page-grey-box-text">
        <div>
            <p>
                In the face of throwaway culture, we strive to create objects that reconcile the functional with the
                ornamental and stand the test of time. Against the march of modernity we forge our own path; retaining
                the means and nourishing the techniques that continue to prove as integral to our ways of working.
            </p>
            <p class="static-page-bigger_text">

                    The world has changed beyond recognition in three centuries, but we endure as proud and
                    uncompromising British manufacturers.

            </p>
        </div>
    </div>
</div>
