<?php
/** @var \Magento\Framework\View\Element\Template $block */
?>
<div class="static-page-content clearfix">
    <div class="static_text_3images">
        <div>
            <h2 class="small-uppertitle">Uncompromising</h2>
            <h1 class="small-underline">Craftsmanship</h1>
            <p>
                Our 300 year history is founded upon a proud tradition of British hand craft. Comprising a team of
                experienced artisans including painters, sculptors and metalworkers, we can ensure the utmost level of
                care and expertise is given to every design made inside our Cotswolds workshop.
            </p>
            <p>
                Our production methods are such that a single piece can travel through up to ten pairs of skilled hands
                by the time it reaches its final form. We believe that this partnership and internal dialogue is one of
                the reasons why our products are so distinctive in character and exceptional in quality.
            </p>
        </div>
        <div class="static_text_3images-images">
            <div class="static_text_3images-images-col-1"><img
                    src="<?= $block->getViewFileUrl('Magento_Cms::images/craftsmanship/uncompromising_1.jpg'); ?>"
                    alt="Uncompromising 1"/></div>
            <div class="static_text_3images-images-col-2">
                <div class="static_text_3images-images-col-2-1"><img
                        src="<?= $block->getViewFileUrl('Magento_Cms::images/craftsmanship/uncompromising_2.jpg'); ?>"
                        alt="Uncompromising 2"></div>
                <div class="static_text_3images-images-col-2-2"><img
                        src="<?= $block->getViewFileUrl('Magento_Cms::images/craftsmanship/uncompromising_3.jpg'); ?>"
                        alt="Uncompromising 3"></div>
            </div>


        </div>
    </div>
</div>
