<?php
/** @var \Magento\Framework\View\Element\Template $block */
?>
<a name="premiumquality"></a>
<div class="static-page-content">
    <div class="cms-bespoke-bottom_content">

        <div class="vertical-side-line-container"><span class="vertical-side-line"><?= __("Our Story"); ?></span></div>

        <img src="<?= $block->getViewFileUrl('Magento_Cms::images/story/premium_quality.jpg'); ?>" alt="Culture"/>

        <div class="static-page-grey-box-text">
            <div >
                <h2 class="small-uppertitle">Premium</h2>
                <h1 class="small-underline">Quality</h1>

                <p>The best lampshades begin with the finest materials. Discover our curated range of luxury fabrics, which are used on all of our in-house lampshades. </p>

                <a href="<?= $block->getUrl('premium-quality') ?>" class="button">Learn more</a>
            </div>
        </div>
    </div>
</div>
