<?php
/** @var \Magento\Framework\View\Element\Template $block */
?>
<div class="static_box_black_text_image">
    <div class="static_box_black_text_image_text_content story_top_box">
        <div class="static_box_black_text_image_text">
            <h2 class="small-uppertitle">Our</h2>
            <h1 class="small-underline">Story</h1>
            <p>
                The Light Shade Studio is a premium British shading brand with over fifty years of combined experience. Our shades are lovingly and individually crafted using traditional hand finishing techniques.. Here you can learn more about our background, explore our high quality range of in-house fabrics and discover the possibilities made available through our fully bespoke service.
            </p>
            <div class="static_box_black_text_image_buttons">
                <a href="#handmadeinbritain" class="button">HANDMADE IN BRITAIN</a>
                <a href="#premiumquality" class="button">PREMIUM QUALITY</a>
                <a href="#bespoke" class="button">BESPOKE ORDERING</a>
            </div>
        </div>
    </div>

    <img src="<?= $block->getViewFileUrl('Magento_Cms::images/story/story.jpg'); ?>" alt="Story"/>
</div>

