<?php
/** @var \Magento\Framework\View\Element\Template $block */
?>
<div class="static-page-content">
    <div class="inside_block_text_and_image static-page-grey-box-text">
        <div class="inside_block_text_content">
            <div class="italic_24_text">Our current delivery times are 2–3 weeks on all products.</div>
            <div>
                <p>
                    Our website is where you can place orders and check stock, either via our trade partners or directly from our online store.

                </p>
                <p>
                    If you require an order to be shipped outside of the UK, please contact us. We remain committed to providing you with the best service possible.
                </p>
            </div>

        </div>
        <img src="<?= $block->getViewFileUrl('Magento_Cms::images/delivery/delivery.jpg'); ?>" alt="Delivery"/>
    </div>
</div>

<div class="center_content">
    <p class="italic_24_text ">For any delivery related questions, please contact us.</p>
    <a href="mailto: sales@thelightshadestudio.co.uk" class="button ">sales@thelightshadestudio.co.uk</a>
</div>
