<?php
/** @var \Magento\Framework\View\Element\Template $block */
?>

<div class="static-page-content clearfix">
    <div class="static_text_3images">
        <div>
            <h2 class="small-uppertitle">Handmade </h2>
            <h1 class="small-underline">in Britain</h1>
            <p>
                Based at our purpose-built atelier in Oxfordshire, our experienced team of shade makers meticulously assemble each of our lampshades using traditional hand-finishing techniques into a multitude of shapes, sizes and colours.
            </p>
            <p>Collectively they share over fifty years of combined experience in this unique craft, and it shows. From bright and bold two-tone hard shades in luxury silk, to sumptuous pleated soft shades complemented with delicate taffeta linings, there is almost nothing that this artistic group cannot create. </p>

        </div>
        <div class="static_text_3images-images">
            <div class="static_text_3images-images-col-1"><img src="<?= $block->getViewFileUrl('Magento_Cms::images/handmade/handmade_1.jpg'); ?>" alt="Bespoke 1"/></div>
            <div class="static_text_3images-images-col-2">
                <div class="static_text_3images-images-col-2-1"><img src="<?= $block->getViewFileUrl('Magento_Cms::images/handmade/handmade_2.jpg'); ?>" alt="Bespoke 2"/></div>
                <div class="static_text_3images-images-col-2-2"><img src="<?= $block->getViewFileUrl('Magento_Cms::images/handmade/handmade_3.jpg'); ?>" alt="Bespoke 3"/></div>
            </div>


        </div>
    </div>
</div>
