<?php
/**
 * @author FYB Romania
 * @copyright Copyright (c) FYB Romania (https://fyb.ro)
 * @package Notification Bar for Magento 2
 */
/** @var $block \Fyb\NotificationBar\Block\Notification */
$minHeight = (int)$block->getConfig('min_height') > 0 ? (int)$block->getConfig('min_height'): 40;
?>
<?php if ($block->needDisplay()): ?>
    <div class="sticky-notification-bar"
         style="background-color: <?php echo $this->getConfig('background_color') ?>;
                color: <?php echo $this->getConfig('text_color') ?>;"
    >
        <div class="content" style="min-height: <?= $minHeight ?>px;"><?php echo $block->getConfig('content') ?></div>
    </div>
    <style>
        <?php echo $block->getConfig("custom_css")?>
    </style>
    <?php if ($block->getConfig('is_sticky')): ?>
        <script>
            window.addEventListener("load", function () {
                var notificationBar = document.getElementsByClassName("sticky-notification-bar")[0];
                var h = Math.max(notificationBar?.clientHeight || 0, 0);

                notificationBar.style.position = "fixed";

                document.getElementsByClassName("page-header")[0].style.marginTop = notificationBar.offsetHeight + "px";
                if (document.getElementsByClassName("homepage-top_text").length) {
                    document.getElementsByClassName("homepage-top_text")[0].style.top = (178 + h) + "px";
                }
            });
        </script>
    <?php else: ?>
        <script>
            window.addEventListener("load", function () {
                var notificationBar = document.getElementsByClassName("sticky-notification-bar")[0];
                var h = Math.max(notificationBar?.clientHeight || 0, 0);

                if (document.getElementsByClassName("homepage-top_text").length) {
                    document.getElementsByClassName("homepage-top_text")[0].style.top = (178 - h) + "px";
                }
            })
        </script>
    <?php endif; ?>

<?php endif; ?>
