<?php
/** @var \Magento\Framework\View\Element\Template $block */
?>

<div class="static-page-content greybox_static_text_one_image">
    <div class="vertical-side-line-container"><span class="vertical-side-line"><?= __("BESPOKE"); ?></span></div>


    <img src="<?= $block->getViewFileUrl('Magento_Cms::images/bespoke/bespoke_4.jpg'); ?>" alt="Culture" />

    <div class="static-page-grey-box-text">
        <div>
            <p>
                Once we have received your swatch, we will assess the fabric before returning it to you with a quote and material quantity in order for us to fulfil your order. For some fabrics such as dupion silks, it is not possible to hand laminate (this is the process of fixing the fabric to the rigid inner lining material). In such cases we can laminate the fabric using a machined process, reducing any bubbling or lifting between the fabric and lining. We require a minimum of 6 metres of fabric for this process.
            </p>

        </div>
    </div>
</div>
