<?php
/** @var \Magento\Framework\View\Element\Template $block */
$customizeHelper = $this->helper(\Fyb\Customizer\Helper\Data::class);
?>
<div class="cms-bespoke-foter_content">
    <div class="cms-bespoke-foter_content_2">

        We are happy to receive fabric samples at the address below.<br/> If you have any questions prior, please contact us at: bespoke@thelightshadestudio.co.uk


    </div>
    <div class="cms-bespoke-foter_content_1">

        The Light Shade Studio<br/>
        Där Lighting Group<br/>
        Wildmere Industrial Estate<br/>
        Banbury<br/>
        Oxon<br/>
        OX16 3JZ<br/><br/>


    </div>
    <div class="cms-bespoke-foter_content_2">


        Please note that unless faulty, bespoke shades are non-refundable in line with our standard terms and
        conditions.


    </div>

</div>
