<div class="static-page-description">
    <span>
        For those who like to be a little different, the range of possibilities we offer is truly exciting.
If you love lampshades as much as we do, you’ll be thrilled to learn that we can offer a fully bespoke service for customers supplying their own fabrics. If you’re looking to add a pop of personality into a room with a daring design, or simply wishing to extend an existing soft furnishing scheme further by coordinating your lighting alongside it, by following a few simple steps we will be able to make your vision a reality.
    </span>
</div>
