<?php
/** @var \Magento\Framework\View\Element\Template $block */
?>

<div class="static-page-content clearfix">
    <div class="static_text_3images">
        <div>
            <h2 class="small-uppertitle">Bespoke</h2>
            <h1 class="small-underline">Ordering</h1>
            <p>
                To ensure safety and suitability, we kindly ask that customers send us a fabric swatch at the address below in order for us to check compatibility with our adhesives and lining materials. The swatch needs to be a minimum size of 10 x 10cm and should also include your contact details alongside so that we can get in touch with any queries prior to production.
            </p>
            <p>You will also need to let us know which shade frame you would like us to use and whether the shade is intended as a ceiling pendant, table or floor lamp shade. If your fabric is patterned or striped we will also need to know the direction you would like the pattern to run; these small details can make a big difference to your finished shade.</p>
            <p>Don’t forget to specify the fabric lining that you would like to use. In most cases, we can use any fabric from our range, as well as a choice of two taffeta silks, or white, gold, silver and bronze laminates. </p>

        </div>
        <div class="static_text_3images-images">
            <div class="static_text_3images-images-col-1"><img  src="<?= $block->getViewFileUrl('Magento_Cms::images/bespoke/bespoke_1.jpg'); ?>" alt="Bespoke 1"/></div>
            <div class="static_text_3images-images-col-2">
                <div class="static_text_3images-images-col-2-1"><img class="img_max_80" src="<?= $block->getViewFileUrl('Magento_Cms::images/bespoke/bespoke_2.jpg'); ?>" alt="Bespoke 2"/></div>
                <div class="static_text_3images-images-col-2-2"><img class="img_max_80" src="<?= $block->getViewFileUrl('Magento_Cms::images/bespoke/bespoke_3.jpg'); ?>" alt="Bespoke 3"/></div>
            </div>


        </div>
    </div>
</div>
