<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php
$_product = $block->getProduct();
$customizeHelper = $this->helper(\Fyb\Customizer\Helper\Data::class);
$storeHelper = $this->helper(\Fyb\Theme\Helper\StoreData::class);
?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if (!$_product->getData('pallet_delivery')): ?>
    <?php if ($_product->isSaleable() && !$customizeHelper->isCustomizable($_product)) :?>
    <div class="box-tocart">
        <div class="fieldset">
            <?php if ($block->shouldRenderQuantity()) :?>
            <div class="field qty">
                <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
                <div id="product-qty" class="control" data-bind="scope: 'qty-counter'">
                    <!-- ko template: getTemplate() --><!-- /ko -->
                    <script type="text/x-magento-init">
                        {
                            "#product-qty": {
                                "Magento_Ui/js/core/app": {
                                    "components": {
                                        "qty-counter": {
                                            "component": "qty-counter",
                                            "config": {
                                                "qty": <?php echo $block->getProductDefaultQty() * 1 ?>,
                                                "dataValidate": <?php echo json_encode($block->getQuantityValidators()) ?>
                                            }
                                        }
                                     }
                                }
                            }
                        }
                    </script>
                </div>
            </div>
            <?php endif; ?>
            <div class="actions">
                <button type="submit"
                        title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                        class="action primary tocart"
                        id="product-addtocart-button" disabled>
                    <span><?= $block->escapeHtml($buttonTitle) ?></span>
                </button>

                <?= $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
    <?php endif; ?>
<?php else: ?>
    <div class="special-delivery">
        <div class="special-delivery-title">
            <span>This item requires special delivery</span>
        </div>
        <div class="special-delivery-text">
            <div><?= $block->escapeHtml("This is an oversized item and will be delivered on a pallet.") ?></div>
            <div><?= $block->escapeHtml("Extra delivery charges apply.") ?></div>
            <div><?= __("Please contact our sales team %1 or call %2 to continue with your order.",
                    $storeHelper->getStoreContactEmail(),
                    $storeHelper->getStorePhone()) ?></div>
            <div>Please quote product code: <span class="special-delivery-sku"><?= $_product->getSku() ?></span></div>
        </div>
    </div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
