<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>

<?php
$_product = $block->getProduct();
$buttonTitle = __('Customise');
$customizeHelper = $this->helper(\Fyb\Customizer\Helper\Data::class);
?>

<?php if ($customizeHelper->isCustomizable($_product)) :?>
<?php
$linkCustomise = $customizeHelper->getCustomizeLink($_product);
?>

<div class="box-customise">
    <a href="<?= $linkCustomise ?>" class="action primary" id="product-customise-button">
        <span><?= $block->escapeHtml($buttonTitle) ?></span>
    </a>
</div>
<?php endif; ?>
