<div class="product-view-finishes">
    <div class="product-view-finishes-text-container">
        <div class="product-view-finishes-text">
            <h1>View Our finishes</h1>
            <p>A perfect synergy between material and process is what really sets David
                Hunt Lighting finishes apart. We have spent decades evolving each and
                every stage of our design process, of which finishing forms a hugely
                significant part.
            </p>
            <a href="<?= $block->getUrl('our-swatches') ?>" class="button">
                View our finishes
            </a>
        </div>
    </div>
    <div class="product-view-finishes-image">
        <img src="<?= $block->getViewFileUrl('Magento_Catalog::images/product_finishes_footer.png'); ?>" alt="Footer Image">
    </div>
</div>
