<?php
$storeHelper = $this->helper('Fyb\Theme\Helper\StoreData');
$apiKey = $storeHelper->getConfig('stockistlocator/general/access_token');
?>

<div class="find-us-content ">
    <div id="map-canvas" class="stockist__left-side" style="height:640px; width:100%;">&nbsp;</div>

    <div class="find-us-content-text">
        <ul>
            <li>
                <h2 style="cursor: pointer;" data-click="0">London Showroom</h2>
                <ul class="find-us-content__address">
                    <li>Monday - Friday</li>
                    <li>09:30 – 17:00</li>
                    <li>+44(0)20 7349 8111</li>
                </ul>
                <ul style="cursor: pointer;" data-click="0" class="find-us-content__address">
                    <li>DAVID HUNT LIGHTING</li>
                    <li>Third Floor, Centre Dome Design Centre,</li>
                    <li>Chelsea Harbour, London SW10 0XE</li>
                </ul>
            </li>
            <li>
                <h2 style="cursor: pointer;" data-click="1">Trade Showroom</h2>
                <ul class="find-us-content__address">
                    <li>(by appointment only)</li>
                    <li>+44(0)1295 672 627</li>
                </ul>
                <ul style="cursor: pointer;" data-click="1" class="find-us-content__address">
                    <li>DAVID HUNT LIGHTING</li>
                    <li>Swan Close Road,Banbury</li>
                    <li>Oxfordshire OX16 5AQ</li>
                </ul>
            </li>
            <li>
                <h2 style="cursor: pointer;" data-click="2">Workshop</h2>
                <ul class="find-us-content__address">
                    <li>(by appointment only)</li>
                    <li>+44(0)1295 672 627</li>
                </ul>
                <ul style="cursor: pointer;" data-click="2" class="find-us-content__address">
                    <li>DAVID HUNT LIGHTING</li>
                    <li>Tilemans Lane, Shipston on Stour</li>
                    <li>Warwickshire CV36 4HP</li>
                </ul>
            </li>
        </ul>
    </div>
</div>


<script type="text/javascript">
    require([
        'jquery',
        'domReady!'
    ], function ($) {
        var curPosition = {
            lat: 51.476257169113865,
            lng: -0.18282858584504952,
        };
        const markerColor = {
            path: "M12,11.5A2.5,2.5 0 0,1 9.5,9A2.5,2.5 0 0,1 12,6.5A2.5,2.5 0 0,1 14.5,9A2.5,2.5 0 0,1 12,11.5M12,2A7,7 0 0,0 5,9C5,14.25 12,22 12,22C12,22 19,14.25 19,9A7,7 0 0,0 12,2Z",
            strokeColor: "#000000",
            fillColor: "#a1a1a1",
            fillOpacity: 1,
            strokeWeight: 0.5,
            rotation: 0,
            scale: 2
        };
        var map = null;
        var mapOptions = {
            zoom: 10,
            disableDefaultUI: true,
            // mapId: 'ce2a11ebf191ec00',
            styles: [
                {
                    "featureType": "administrative",
                    "elementType": "all",
                    "stylers": [
                        {
                            "saturation": "-100"
                        }
                    ]
                },
                {
                    "featureType": "administrative.province",
                    "elementType": "all",
                    "stylers": [
                        {
                            "visibility": "off"
                        }
                    ]
                },
                {
                    "featureType": "landscape",
                    "elementType": "all",
                    "stylers": [
                        {
                            "saturation": -100
                        },
                        {
                            "lightness": 65
                        },
                        {
                            "visibility": "on"
                        }
                    ]
                },
                {
                    "featureType": "poi",
                    "elementType": "all",
                    "stylers": [
                        {
                            "visibility": "off"
                        }
                    ]
                },
                {
                    "featureType": "road",
                    "elementType": "all",
                    "stylers": [
                        {
                            "saturation": "-100"
                        }
                    ]
                },
                {
                    "featureType": "road.highway",
                    "elementType": "all",
                    "stylers": [
                        {
                            "visibility": "simplified"
                        }
                    ]
                },
                {
                    "featureType": "road.highway",
                    "elementType": "labels",
                    "stylers": [
                        {
                            "saturation": "-12"
                        },
                        {
                            "lightness": "12"
                        },
                        {
                            "visibility": "on"
                        },
                        {
                            "weight": "4.11"
                        }
                    ]
                },
                {
                    "featureType": "road.highway",
                    "elementType": "labels.icon",
                    "stylers": [
                        {
                            "visibility": "simplified"
                        }
                    ]
                },
                {
                    "featureType": "road.highway.controlled_access",
                    "elementType": "all",
                    "stylers": [
                        {
                            "visibility": "simplified"
                        }
                    ]
                },
                {
                    "featureType": "transit",
                    "elementType": "all",
                    "stylers": [
                        {
                            "saturation": -100
                        },
                        {
                            "visibility": "simplified"
                        }
                    ]
                },
                {
                    "featureType": "water",
                    "elementType": "geometry",
                    "stylers": [
                        {
                            "hue": "#ffff00"
                        },
                        {
                            "lightness": -25
                        },
                        {
                            "saturation": -97
                        }
                    ]
                },
                {
                    "featureType": "water",
                    "elementType": "labels",
                    "stylers": [
                        {
                            "lightness": -25
                        },
                        {
                            "saturation": -100
                        }
                    ]
                }
            ]
        }

        var points = [
            {
                lat: 51.476257169113865,
                lng: -0.18282858584504952,
                title: 'London Showroom',
                info: '<h4>London Showroom</h4>' +
                    'Monday - Friday</br>' +
                    '<span>09:30 – 17:00</span></br>' +
                    '<span>+44(0)20 7349 8111</span></br>' +
                    '<span>DAVID HUNT LIGHTING</span></br>' +
                    '<span>Third Floor, Centre Dome Design Centre,</span></br>' +
                    '<span>Chelsea Harbour, London SW10 0XE</span>'
            },
            {
                lat: 52.05815950176155,
                lng: -1.3324027510213512,
                title: 'Trade Showroom',
                info: '<h4>Trade Showroom</h4></br>' +
                    '<span>(by appointment only)</span></br>' +
                    '<span>+44(0)1295 672 627</span></br>' +
                    '<span>DAVID HUNT LIGHTING</span></br>' +
                    '<span>Swan Close Road,Banbury</span></br>' +
                    '<span>Oxfordshire OX16 5AQ</span>'
            },
            {
                lat: 52.06678014743098,
                lng: -1.6267927379489704,
                title: 'Workshop',
                info: '<h4>Workshop</h4></br>' +
                    '<span>DAVID HUNT LIGHTING</span></br>' +
                    '<span>Tilemans Lane, Shipston on Stour</span></br>' +
                    '<span>Warwickshire CV36 4HP</span>'
            }
        ];

        var allInfoWindows = [];
        function mapLoadedFunc() {
            mapOptions.center = new google.maps.LatLng(curPosition.lat, curPosition.lng);

            map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);

            $.each(points, function (key, point) {
                var myLatlng = new google.maps.LatLng(point.lat, point.lng);
                var marker = new google.maps.Marker({
                    position: myLatlng,
                    map: map,
                    icon: markerColor,
                    title: point.title.toUpperCase()
                });

                var infowindow = new google.maps.InfoWindow({
                    content: point.info
                });
                allInfoWindows.push(infowindow);
                $('[data-click=' + key + ']').on('click', function() {
                    goToMarker(marker, infowindow);
                });
                google.maps.event.addListener(marker, 'click', function () {
                    goToMarker(marker, infowindow);
                });
            });
        }

        function goToMarker(marker, infowindow) {
            map.setZoom(10);
            map.panTo(marker.position);
            allInfoWindows.forEach(function (info) {
                info.close();
            })
            infowindow.open(map, marker);
        }

        var apiKey = "<?= $apiKey ?>";
        if (!apiKey) {
            return;
        }
        window['mapLoadedFunc'] = mapLoadedFunc.bind(this);

        let s = document.createElement("script");
        s.type = "text/javascript";
        s.async = true;
        s.defer = true;
        s.src = "https://maps.googleapis.com/maps/api/js?key=" + apiKey + "&sensor=true&libraries=marker&callback=mapLoadedFunc";
        window.document.body.append(s);
    });
</script>
