<?php
/** @var \Magento\Framework\View\Element\Template $block */
?>

<?php
$contents = [
    [
        'image' => $block->getViewFileUrl('Magento_Cms::images/heritage/Heritage-1.jpg'),
        'title' => '1687',
        'sub_title' => 'Ten Generations: Two Traditions',
        'content' => 'The earliest recorded member of the Hunt family was John Hunt, born in 1687 and listed as a master brass founder, making fine candlesticks during the reign of the Hanoverian dynasty.
Throughout the last three centuries, ten generations of the Hunt family have adapted to a rapidly modernising world, but two traditions have remained a constant: the eldest son of each generation has been named John and all have manufactured fine lighting.',
    ],
    [
        'image' => $block->getViewFileUrl('Magento_Cms::images/heritage/Heritage-2.jpg'),
        'title' => '1851',
        'sub_title' => 'Entrepreneurs & Exhibitors',
        'content' => 'The late 1700s brought with it the Industrial Revolution, and quiet cottage industries became futurescapes of whirring machinery. During this time, the Hunt family thrived and were selected to exhibit their products at Prince Albert’s Great Exhibition under the glass domes of Crystal Palace in 1851. Quick to adapt to new technologies, the company pivoted from candlesticks to outdoor gas lamps, lighting the streets of nineteenth century Britain. They also became leaders in electroplating by the 1890s. ',
    ],
    [
        'image' => $block->getViewFileUrl('Magento_Cms::images/heritage/Heritage-3.jpg'),
        'title' => '1930',
        'sub_title' => 'On The Grid',
        'content' => 'In 1926 Britain’s patchwork of small supply networks was transformed into the National Grid; electric light was finally available to everyone. Luckily our factory, then based in Bradford Street, Birmingham had already converted its machinery to become one of the first manufacturers of electric lighting a decade prior. The Hunt family became renowned for their electric light fittings, made in the new Art Deco style and installed at the first Odeon cinemas in the 1930s, which became a key feature of the dramatic maritime-inspired lobbies.',
    ],
    [
        'image' => $block->getViewFileUrl('Magento_Cms::images/heritage/Heritage-4.jpg'),
        'title' => '1960',
        'sub_title' => 'The Spinning Sixties',
        'content' => 'The late 1950s saw a long-awaited revival of design, manufacture and innovation. The post-war shortages of labour and raw materials were finally at an end, and a young David Hunt founded our current factory in Shipston-on-Stour, on the northern edge of the Cotswolds. Experimenting with new technologies, the company became leaders in resin casting and spun metal, creating design classics that typified this new and futuristic era.',
    ],
    [
        'image' => $block->getViewFileUrl('Magento_Cms::images/heritage/Heritage-5.jpg'),
        'title' => '1980',
        'sub_title' => 'A Victorian Revival',
        'content' => 'The 1980s saw a return to more traditional British interiors – a crucial point in our company history. John Peter Hunt, the tenth generation of our namesake, began to rescue Victorian gas light designs from the company archives. Adapted to twentieth century manufacturing techniques and electrical standards, these collections anchor David Hunt Lighting to its past and have remained best-sellers for over four decades.',
    ],
    [
        'image' => $block->getViewFileUrl('Magento_Cms::images/heritage/Heritage-6.jpg'),
        'title' => '2000',
        'sub_title' => 'A Timeless British Brand',
        'content' => 'At the dawn of the millennium, David Hunt Lighting became part of the där lighting group. Over the past two decades the company has worked tirelessly to build an exclusive partner network comprising Britain’s finest lighting showrooms, offering a range of bespoke services for interior designers, architects and consumers alike.',
    ],
    [
        'image' => $block->getViewFileUrl('Magento_Cms::images/heritage/Heritage-7.jpg'),
        'title' => '2011',
        'sub_title' => '',
        'content' => 'Decorex Awards: Nominee for Best British manufacturer',
    ],
    [
        'image' => $block->getViewFileUrl('Magento_Cms::images/heritage/Heritage-8.jpg'),
        'title' => '2014',
        'sub_title' => '',
        'content' => 'Launch of the first David Hunt Lighting website: <a href="www.davidhuntlighting.co.uk">www.davidhuntlighting.co.uk</a>',
    ],
    [
        'image' => $block->getViewFileUrl('Magento_Cms::images/heritage/Heritage-9.jpg'),
        'title' => '2016',
        'sub_title' => '',
        'content' => 'The English Home editor’s choice award winner: Sputnik table lamp',
    ],
    [
        'image' => $block->getViewFileUrl('Magento_Cms::images/heritage/Heritage-10.jpg'),
        'title' => '2017',
        'sub_title' => 'Awards',
        'content' => '<ul>
                <li>The International Design & Architecture Awards shortlist: Sputnik pendant</li>
                <li>LUX Global Excellence Awards nominee: Hyde Pendant</li>
            </ul>',
    ],
    [
        'image' => $block->getViewFileUrl('Magento_Cms::images/heritage/Heritage-11.jpg'),
        'title' => '2018',
        'sub_title' => 'Awards',
        'content' => '<ul>
                <li>The English Home New Year’s Honours List winner: Lighting category</li>
                <li>The International Design & Architecture Awards shortlist: Hyde pendant</li>
            </ul>',
    ],
    [
        'image' => $block->getViewFileUrl('Magento_Cms::images/heritage/Heritage-12.jpg'),
        'title' => '2019',
        'sub_title' => '',
        'content' => 'Launch of our first London showroom at The Design Centre Chelsea Harbour',
    ],
    [
        'image' => $block->getViewFileUrl('Magento_Cms::images/heritage/Heritage-13.jpg'),
        'title' => '2021',
        'sub_title' => 'Awards',
        'content' => '<ul>
                <li>Featured in the Financial Times ‘Light Fantastic’ feature: Liberty pendant</li>
                <li>LivingEtc Style Awards 2021 nominee: Hyde pendant</li>
            </ul>',
    ],
    [
        'image' => $block->getViewFileUrl('Magento_Cms::images/heritage/Heritage-14.jpg'),
        'title' => '2022',
        'sub_title' => '',
        'content' => 'The English Home New Year’s Honours List nominee: Gingko table lamp',
    ],
    [
        'image' => $block->getViewFileUrl('Magento_Cms::images/heritage/Heritage-15.jpg'),
        'title' => '2023',
        'sub_title' => '',
        'content' => 'Launch of our newly renovated larger showroom at The Design Centre Chelsea Harbour',
    ],
    [
        'image' => $block->getViewFileUrl('Magento_Cms::images/heritage/Heritage-16.jpg'),
        'title' => '2024',
        'sub_title' => '',
        'content' => 'Launch of our new website: <a href="www.davidhuntlighting.co.uk">www.davidhuntlighting.co.uk</a>',
    ],
];

$contents = array_reverse($contents);
$contentCount = count($contents) - 1;
?>


<div class="heritage-content">
    <div class="divider-timeline-top">
        <div class="divider-timeline-round"></div>
        <div class="divider-timeline-long"></div>
    </div>
    <?php foreach ($contents as $key => $content): ?>
        <?php $realKey = $contentCount - $key; ?>
        <div class="block <?= ($realKey % 2 != 0) ? 'block-gray' : '' ?>">
            <div class="timeline-line">
                <?php if ($realKey % 2 == 0): ?>
                <?php //$block->getViewFileUrl('Magento_Cms::images/heritage/heritage_' . ($realKey + 1) . '.png'); ?>
                    <div class="block-image">
                        <img
                            src="<?= __($content['image']) ?>"
                            alt="Our Heritage <?= $key ?>">
                    </div>
                    <div class="divider-timeline">
                        <div class="divider-timeline-long"></div>
                        <div class="divider-timeline-short"></div>
                        <div class="divider-timeline-long"></div>
                    </div>
                    <div class="block-content">
                        <h2><?= __($content['title']) ?></h2>
                        <?php if ($content['sub_title']): ?>
                            <span class="subtitle"><?= __($content['sub_title']) ?></span>
                        <?php endif; ?>
                        <p>
                            <?= $content['content'] ?>
                        </p>
                    </div>
                <?php else: ?>
                    <div class="block-content">
                        <h2><?= __($content['title']) ?></h2>
                        <?php if ($content['sub_title']): ?>
                            <span class="subtitle"><?= __($content['sub_title']) ?></span>
                        <?php endif; ?>
                        <p>
                            <?= $content['content'] ?>
                        </p>
                    </div>
                    <div class="divider-timeline">
                        <div class="divider-timeline-long"></div>
                        <div class="divider-timeline-short"></div>
                        <div class="divider-timeline-long"></div>
                    </div>
                    <div class="block-image">
                        <img
                            src="<?= __($content['image']) ?>"
                            alt="Our Heritage <?= $key ?>">
                    </div>
                <?php endif; ?>
            </div>
        </div>
    <?php endforeach; ?>
    <div class="divider-timeline-top">

        <div class="divider-timeline-long"></div>
        <div class="divider-timeline-round"></div>
    </div>
</div>
